@echo off

set "LibName=lib_CUDAD"

mkdir %LibName%

cmake -S ./Source -B ./%LibName%  -DCMAKE_BUILD_TYPE=Release -DAMReX_PRECISION=DOUBLE -DAMReX_GPU_BACKEND=CUDA   -DAMReX_MPI=OFF   -DAMReX_FORTRAN=OFF   -DAMReX_EB=EB  -DAMReX_PARTICLES=OFF  -DAMReX_LINEAR_SOLVERS_EM=OFF -DAMReX_AMRLEVEL=OFF -DAMReX_LINEAR_SOLVERS_INCFLO=OFF -DAMReX_LINEAR_SOLVERS=OFF    -DCMAKE_CUDA_COMPILER=nvcc  

cmake --build %LibName% --config Release -j 32

echo AMReX Library Builded
pause
