cd ./External/amrex

cmake -S ./source -B ./lib_CUDA  -DCMAKE_BUILD_TYPE=Release -DAMReX_PRECISION=SINGLE -DAMReX_GPU_BACKEND=CUDA   -DAMReX_MPI=OFF   -DAMReX_FORTRAN=OFF   -DAMReX_EB=EB  -DAMReX_PARTICLES=OFF -DAMReX_LINEAR_SOLVERS_EM=OFF -DAMReX_AMRLEVEL=OFF -DAMReX_LINEAR_SOLVERS_INCFLO=OFF -DAMReX_LINEAR_SOLVERS=OFF   -DCMAKE_CUDA_COMPILER=nvcc  
cmake --build lib_CUDA --config Release -j32

cmake -S ./source -B ./lib_CUDAD  -DCMAKE_BUILD_TYPE=Release -DAMReX_PRECISION=DOUBLE -DAMReX_GPU_BACKEND=CUDA   -DAMReX_MPI=OFF   -DAMReX_FORTRAN=OFF   -DAMReX_EB=EB  -DAMReX_PARTICLES=OFF  -DAMReX_LINEAR_SOLVERS_EM=OFF -DAMReX_AMRLEVEL=OFF -DAMReX_LINEAR_SOLVERS_INCFLO=OFF -DAMReX_LINEAR_SOLVERS=OFF    -DCMAKE_CUDA_COMPILER=nvcc  
cmake --build lib_CUDAD --config Release -j32

cmake -S ./source -B ./lib_MPI  -DCMAKE_BUILD_TYPE=Release  -DAMReX_FORTRAN=OFF   -DAMReX_EB=EB  -DAMReX_PARTICLES=OFF   -DAMReX_LINEAR_SOLVERS_EM=OFF -DAMReX_AMRLEVEL=OFF -DAMReX_LINEAR_SOLVERS_INCFLO=OFF -DAMReX_LINEAR_SOLVERS=OFF  
cmake --build lib_MPI --config Release -j32

cmake -S ./Source -B ./lib_DFT -DAMReX_MPI=OFF  -DCMAKE_BUILD_TYPE=Release  -DAMReX_FORTRAN=OFF   -DAMReX_EB=EB  -DAMReX_PARTICLES=OFF   -DAMReX_LINEAR_SOLVERS_EM=OFF -DAMReX_AMRLEVEL=OFF -DAMReX_LINEAR_SOLVERS_INCFLO=OFF -DAMReX_LINEAR_SOLVERS=OFF  
cmake --build lib_DFT --config Release -j 32

cmake -S ./source -B ./lib_MCUDA  -DCMAKE_BUILD_TYPE=Release -DAMReX_PRECISION=SINGLE -DAMReX_GPU_BACKEND=CUDA   -DAMReX_MPI=ON   -DAMReX_FORTRAN=OFF   -DAMReX_EB=EB  -DAMReX_PARTICLES=OFF -DAMReX_LINEAR_SOLVERS_EM=OFF -DAMReX_AMRLEVEL=OFF -DAMReX_LINEAR_SOLVERS_INCFLO=OFF -DAMReX_LINEAR_SOLVERS=OFF   -DCMAKE_CUDA_COMPILER=nvcc  
cmake --build lib_MCUDA --config Release -j32

cmake -S ./source -B ./lib_MCUDAD  -DCMAKE_BUILD_TYPE=Release -DAMReX_PRECISION=DOUBLE -DAMReX_GPU_BACKEND=CUDA   -DAMReX_MPI=ON   -DAMReX_FORTRAN=OFF   -DAMReX_EB=EB  -DAMReX_PARTICLES=OFF  -DAMReX_LINEAR_SOLVERS_EM=OFF -DAMReX_AMRLEVEL=OFF -DAMReX_LINEAR_SOLVERS_INCFLO=OFF -DAMReX_LINEAR_SOLVERS=OFF    -DCMAKE_CUDA_COMPILER=nvcc  
cmake --build lib_MCUDAD --config Release -j32



cmake -B build -DLBM_RUN=MPI -DLBM_TESTS=ON
cmake --build build --config Release -j32
rm -r build

cmake -B build -DLBM_RUN=GPU -DLBM_TESTS=ON
cmake --build build --config Release -j32
rm -r build

cmake -B build -DLBM_RUN=GPUD -DLBM_TESTS=ON
cmake --build build --config Release -j32
rm -r build
